[workspace]
resolver = "2"
members = [
    "contracts/gist-registry",
    "contracts/gist-vault",
    "contracts/location-verifier",
    "tools/reconcile-vault",
]

[workspace.dependencies]
soroban-sdk = "21.0.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "debuginfo"
lto = true
codegen-units = 1
panic = "abort"

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
